[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cwind_frontend"
version = "0.0.1"
authors = [
    { name = "星灿长风v(StarWindv)", email = "starwindv.stv@gmail.com"}
]
license = { text = "BSD-3" }
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ariadne_py @ git+https://github.com/starwindv/ariadne-py",
]

[project.scripts]
cwindf = "cwind_frontend.cli:main"

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true

[tool.setuptools.package-data]
cwind_frontend = ["sa/*.toml"]
